#!/usr/bin/perl
# [[[ HEADER ]]]
use RPerl;

use strict;
use warnings;
our $VERSION = 0.001_000;

# [[[ CRITICS ]]]
## no critic qw(ProhibitUselessNoCritic ProhibitMagicNumbers RequireCheckedSyscalls)
## no critic qw(RequireInterpolationOfMetachars)

# [[[ SUBROUTINES ]]]
our integer $foo = sub {
    ( my string $bar, TERMINAL = HASH(0x7532c88) integer $bat, TERMINAL = HASH(0x75333d8) integer $baz ) = @ARG;
    print $bar, "\n";
    return $bat + $baz;
};

# [[[ OPERATIONS ]]]
foo( 'howdy!', 23, 42 );
