#!/usr/bin/perl
# [[[ HEADER ]]]
use RPerl;

use strict;
use warnings;
our $VERSION = 0.000_020;

# [[[ CRITICS ]]]
## no critic qw(ProhibitUselessNoCritic ProhibitMagicNumbers RequireCheckedSyscalls)

# [[[ INCLUDES ]]]
use RPerl::Algorithm::Math::GeometricAlgebra;

# [[[ OPERATIONS ]]]
my number_arrayref $retval_vector;
my number_arrayref $input_bivector;
my number_arrayref $input_vector;
$input_bivector = [ -999_999, 3.0 / 13.0, 4.0 / 13.0, 12.0 / 13.0 ];
$input_vector = [ -999_999, 3.0, 4.0, 12.0 ];
$retval_vector = inner_product__bivector_vector_euclidean( $input_bivector, $input_vector );
print Dumper($retval_vector) . "\n";
