#!/usr/bin/perl
# [[[ HEADER ]]]
use RPerl;

use strict;
use warnings;
our $VERSION = 0.001_000;

# [[[ CRITICS ]]]
## no critic qw(ProhibitUselessNoCritic ProhibitMagicNumbers RequireCheckedSyscalls)
## no critic qw(RequireInterpolationOfMetachars)

# [[[ OPERATIONS ]]]
foreach my integer $i ( @{ [ my integer $TYPED_i0 = 10, 20, 30, 40, 50 ] } ) {
    print '$i = ', $i, "\n";
}
