#!/usr/bin/perl
# [[[ HEADER ]]]
use RPerl;

use strict;
use warnings;
our $VERSION = 0.001_000;

# [[[ CRITICS ]]]
## no critic qw(ProhibitUselessNoCritic ProhibitMagicNumbers RequireCheckedSyscalls)
## no critic qw(RequireInterpolationOfMetachars)

# [[[ OPERATIONS ]]]
my integer_arrayref_arrayref $rows_and_columns_2D = [
    [ 0, 2, 4, 6, 8 ],
    [ 1, 3, 5, 7, 9 ],
    [ 4, 3, 2, 1, 0 ],
    [ 9, 8, 7, 6, 5 ],
    [ 5, 5, 5, 5, 5 ],
    [ 0, 2, 4, 6, 8 ],
    [ 1, 3, 5, 7, 9 ],
    [ 4, 3, 2, 1, 0 ],
    [ 9, 8, 7, 6, 5 ],
    [ 5, 5, 5, 5, 5 ]
];
my integer $row_3_column_0_combined = $rows_and_columns_2D->[3]->[0];
print 'have $row_3_column_0_combined = ', $row_3_column_0_combined, "\n";
my integer_arrayref $row_3 = $rows_and_columns_2D->[3];
print 'have $row_3 = ', integer_arrayref_to_string($row_3), "\n";
my integer $row_3_column_0_separated = $row_3->[0];
print 'have $row_3_column_0_separated = ', $row_3_column_0_separated, "\n";
