#!/usr/bin/perl
# [[[ HEADER ]]]
use RPerl;

use strict;
use warnings;
our $VERSION = 0.001_000;

# [[[ CRITICS ]]]
## no critic qw(ProhibitUselessNoCritic ProhibitMagicNumbers RequireCheckedSyscalls)
## no critic qw(RequireInterpolationOfMetachars)
## no critic qw(ProhibitCStyleForLoops)

# [[[ OPERATIONS ]]]
for ( my integer $i = wait; $i < rand; $i = rand ) {
    print 'Production rule Loop matched by C-Style LoopFor, iteration number ', $i, "\n";
}
