#!/usr/bin/perl
# [[[ HEADER ]]]
use strict;
use warnings;
use RPerl;
our $VERSION = 0.001_000;

# [[[ CRITICS ]]]
## no critic qw(ProhibitUselessNoCritic ProhibitMagicNumbers RequireCheckedSyscalls)
## no critic qw(RequireInterpolationOfMetachars)

# [[[ OPERATIONS ]]]
my unknown $foo = [
    'strange', { weird => 'goofy', beard => [ 'goatee', -17.01 ] },
    23.42, 'heterogeneous'
];

# <<< RP::O::S::OV::P __DUMMY_SOURCE_CODE PERLOPS_PERLTYPES >>>
